---
title: "CLHS FFL"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r libraries ,include=FALSE}
## Be sure to run the ESPN Scrape before running this

library(flexdashboard)
library(htmlwidgets)
library(jsonlite)
library(gridExtra)
library(readr)
library(ggthemes)
library(scales)
library(zoo)
library(knitr)
library(kableExtra)
library(RColorBrewer)
library(shiny)
library(DT)
library(rsconnect)
library(httr)
library(tidyverse)

options(dplyr.summarise.inform=F)

```

```{r ReadData ,include=FALSE}
## Getting a dataset that has a name with each team by year
TeamNameData <- read_csv("Team Name.csv")
OwnerNameData <- read_csv("Owner Name.csv")
SettingsData <- read_csv("Settings.csv")
DraftOrderData <- read_csv("Draft Order.csv")
TransactionData <- read_csv("Transactions.csv")
OwnerTeamData <- read_csv("Owner and Teams.csv")
LongWeeklyScores <- read_csv("Scoreboard.csv")

## Override Games
## There will hopefully only ever be one of these
## Jared & Luke tied in the playoffs but the tiebreaker was not the usual regular season one
## Because of that, the tiebreak field is not working & both teams are getting a win as a result
OverrideGames <- tibble(
  seasonId = c(2017)
  ,matchupPeriodId = c(15)
  ,ScheduleId = c(99)
  ,TeamId = c(3)
  ,WinOverride = c(0)
)

## Getting data into the correct format for all the charts
PlayoffWeekStart <- SettingsData %>%
  mutate(PlayoffStartWeek = settings.scheduleSettings.matchupPeriodCount + 1) %>% 
  select(seasonId ,PlayoffStartWeek)
  
LongScoringDataTemp <- LongWeeklyScores %>%
  select(seasonId:firstName ,PickNumber ,TeamName) %>%
  mutate(firstName  = str_trim(firstName)) %>%
  left_join(PlayoffWeekStart ,by = "seasonId") %>%
  left_join(OverrideGames ,by = c("seasonId" ,"matchupPeriodId" ,"ScheduleId" ,"TeamId")) %>% 
  group_by(seasonId ,ScheduleId) %>%
  mutate(WinningPoints    = max(TotalPoints ,na.rm = TRUE)
         ,LosingPoints    = min(TotalPoints ,na.rm = TRUE)
         ,WinningTiebreak = max(Tiebreak ,na.rm = TRUE)
         ,LosingTiebreak  = min(Tiebreak ,na.rm = TRUE)
         ,Win             = if_else(WinningPoints == LosingPoints 
                                    ,if_else(Tiebreak == WinningTiebreak ,coalesce(WinOverride ,1) ,0) 
                                    ,if_else(TotalPoints == WinningPoints ,coalesce(WinOverride ,1) ,0)
                                    )
         ,WeekType        = if_else(matchupPeriodId >= PlayoffStartWeek ,"Playoffs" ,"Regular")
         ,OpposingPoints  = if_else(TotalPoints == WinningPoints ,LosingPoints ,WinningPoints)
         ) %>%
  select(-contains("Winning") ,-contains("Losing") ,-PlayoffStartWeek) %>%
  select(seasonId:TotalPoints ,OpposingPoints ,everything()) %>%
  ungroup() %>%
  filter(!is.na(TeamId)) %>%
  group_by(seasonId ,matchupPeriodId) %>%
  arrange(seasonId ,matchupPeriodId ,TotalPoints) %>%
  mutate(WeekRank = rank(TotalPoints) - 1
         ,MaxRank = max(WeekRank)
         ,ExpWins = WeekRank / MaxRank) %>%
  ungroup()

## There's a cleaner way of doing this
## Was very tired of the script by this point
WeekTypeData <- LongScoringDataTemp %>% 
  left_join(OwnerTeamData %>% select(seasonId ,TeamId ,PlayoffAppearance) ,by = c("seasonId" ,"TeamId")) %>% 
  left_join(SettingsData %>% select(seasonId ,settings.scheduleSettings.matchupPeriodCount) ,by = "seasonId") %>% 
  select(seasonId ,TeamId ,firstName ,matchupPeriodId ,ScheduleId ,WeekType ,Win ,PlayoffAppearance ,settings.scheduleSettings.matchupPeriodCount) %>% 
  arrange(TeamId ,seasonId ,matchupPeriodId) %>% 
  mutate(PriorWeekResult = lag(Win)
         ,WeekType2 = if_else(WeekType == "Regular" 
                              ,WeekType 
                              ,if_else(PlayoffAppearance == 0
                                       ,"Consolation"
                                       ,if_else(PriorWeekResult == 0 & settings.scheduleSettings.matchupPeriodCount != matchupPeriodId - 1 
                                                ,"Consolation"
                                                ,"Playoffs"
                                                )
                                       )
                              )
         ,PriorWeekType2 = lag(WeekType2)
         ,WeekType3      = if_else(WeekType2 == "Regular"
                                   ,WeekType2
                                   ,if_else(PriorWeekType2 == "Consolation"
                                            ,"Consolation"
                                            ,WeekType2
                                            )
                                   )
         ) %>% 
  select(seasonId ,matchupPeriodId ,ScheduleId ,TeamId ,WeekType3) %>% 
  rename(WeekType = WeekType3)

LongScoringData <- LongScoringDataTemp %>% 
  select(-WeekType) %>% 
  left_join(WeekTypeData ,by = c("seasonId" ,"matchupPeriodId" ,"ScheduleId" ,"TeamId"))

PlayerNames <- LongScoringData %>%
  select(firstName) %>%
  arrange(firstName) %>%
  distinct() %>%
  pull()

SeasonYears <- LongScoringData %>%
  select(seasonId) %>%
  arrange(seasonId) %>%
  distinct() %>%
  pull()

TopWinPercentPlayer <- LongScoringData %>%
  filter(WeekType == "Regular") %>%
  group_by(firstName) %>%
  summarise(ExpWins        = sum(ExpWins)
            ,ActualWins    = sum(Win)
            ,Diff          = ActualWins - ExpWins
            ,Points        = sum(TotalPoints)
            ,OppPoints     = sum(OpposingPoints)
            ,GamesPlayed   = n()
            ,ExpWinPercent = ExpWins / GamesPlayed
            ,ActWinPercent = ActualWins / GamesPlayed
            ) %>%
  arrange(desc(ActWinPercent) ,desc(ExpWins) ,desc(Points)) %>%
  ungroup() %>% 
  slice(1) %>% 
  select(firstName) %>%
  pull()

AllMatchupOptions <- LongScoringData %>% 
  select(seasonId ,matchupPeriodId ,ScheduleId ,firstName) %>%
  rename(Opponent = firstName) %>% 
  distinct()

OpponentData <- AllMatchupOptions %>% 
  left_join(LongScoringData ,by = c("seasonId" ,"matchupPeriodId" ,"ScheduleId")) %>% 
  rename(Owner = firstName) %>% 
  filter(Owner != Opponent) %>% 
  select(seasonId ,matchupPeriodId ,WeekType ,ScheduleId ,Owner ,Opponent ,TotalPoints ,OpposingPoints ,Win) %>% 
  mutate(PointMargin = TotalPoints - OpposingPoints)

Champion <- OwnerTeamData %>% 
  filter(Championship == 1) %>% 
  mutate(Champion = str_c(FullName ," (" ,TeamName ,")")) %>% 
  select(seasonId ,Champion)

BestTeam <- LongScoringData %>%
  filter(WeekType == "Regular") %>% 
  group_by(seasonId ,firstName) %>% 
  summarise(ExpWins        = sum(ExpWins)
            ,Count         = n()
            ,ExpWinPercent = ExpWins / Count) %>% 
  ungroup() %>% 
  group_by(seasonId) %>% 
  mutate(MaxExpWins        = max(ExpWins)
         ,MaxExpWinPercent = max(ExpWinPercent)) %>% 
  ungroup() %>% 
  filter(ExpWins == MaxExpWins) %>% 
  mutate(BestTeam = str_c(firstName 
                          ," - " 
                          ,round(ExpWins ,digits = 1) 
                          ," expected wins ("
                          ,round(ExpWinPercent * 100 ,digits = 1)
                          ,"%)"
                          )
         ) %>% 
  select(seasonId ,BestTeam)

TopScorer <- LongScoringData %>%
  filter(WeekType == "Regular") %>% 
  group_by(seasonId ,firstName) %>% 
  summarise(TotalPoints = sum(TotalPoints)
            ,TotalGames = n()
            ,AvgPoints  = TotalPoints / TotalGames) %>% 
  ungroup() %>% 
  group_by(seasonId) %>% 
  mutate(MaxTotalPoints = max(TotalPoints)) %>% 
  ungroup() %>% 
  filter(TotalPoints == MaxTotalPoints) %>% 
  mutate(TopScorer = str_c(firstName 
                           ," - " 
                           ,format(round(TotalPoints ,digits = 0) ,big.mark = ",")
                           ," total points ("
                           ,round(AvgPoints ,digits = 1)
                           ," avg)"
                           )
         ) %>% 
  select(seasonId ,TopScorer)

WorstTeam <- LongScoringData %>%
  filter(WeekType == "Regular") %>% 
  group_by(seasonId ,firstName) %>% 
  summarise(ExpWins        = sum(ExpWins)
            ,Count         = n()
            ,ExpWinPercent = ExpWins / Count) %>% 
  ungroup() %>% 
  group_by(seasonId) %>% 
  mutate(MinExpWins        = min(ExpWins)
         ,MinExpWinPercent = min(ExpWinPercent)) %>% 
  ungroup() %>% 
  filter(ExpWins == MinExpWins) %>% 
  mutate(WorstTeam = str_c(firstName 
                           ," - " 
                           ,round(ExpWins ,digits = 1) 
                           ," expected wins ("
                           ,round(ExpWinPercent * 100 ,digits = 1)
                           ,"%)"
                           )
         ) %>% 
  select(seasonId ,WorstTeam)

LowestScorer <- LongScoringData %>%
  filter(WeekType == "Regular") %>% 
  group_by(seasonId ,firstName) %>% 
  summarise(TotalPoints = sum(TotalPoints)
            ,TotalGames = n()
            ,AvgPoints  = TotalPoints / TotalGames) %>% 
  ungroup() %>% 
  group_by(seasonId) %>% 
  mutate(MinTotalPoints = min(TotalPoints)) %>% 
  ungroup() %>% 
  filter(TotalPoints == MinTotalPoints) %>% 
  mutate(LowestScorer = str_c(firstName 
                              ," - " 
                              ,format(round(TotalPoints ,digits = 0) ,big.mark = ",")
                              ," total points ("
                              ,round(AvgPoints ,digits = 1)
                              ," avg)"
                              )
         ) %>% 
  select(seasonId ,LowestScorer)

## There was a tie for the luckiest team back in 2018
## Should probably incorporate this logic into the other table columns at some point
LuckiestTeam <- LongScoringData %>%
  filter(WeekType == "Regular") %>% 
  group_by(seasonId ,firstName) %>% 
  summarise(ExpWins             = sum(ExpWins)
            ,ActualWins         = sum(Win)
            ,ActualMinusExpWins = ActualWins - ExpWins
            ) %>% 
  ungroup() %>% 
  group_by(seasonId) %>% 
  mutate(MaxActualMinusExpWins = max(ActualMinusExpWins)) %>% 
  ungroup() %>% 
  filter(ActualMinusExpWins == MaxActualMinusExpWins) %>%
  group_by(ActualMinusExpWins ,seasonId) %>% 
  summarise(firstName = str_c(firstName ,collapse = " & ")) %>% 
  mutate(LuckiestTeam = str_c(firstName 
                              ," - " 
                              ,round(ActualMinusExpWins ,digits = 1) 
                              ," wins above expected"
                              )
         ) %>% 
  ungroup() %>% 
  select(seasonId ,LuckiestTeam)

UnluckiestTeam <- LongScoringData %>%
  filter(WeekType == "Regular") %>% 
  group_by(seasonId ,firstName) %>% 
  summarise(ExpWins             = sum(ExpWins)
            ,ActualWins         = sum(Win)
            ,ActualMinusExpWins = ActualWins - ExpWins
            ) %>% 
  ungroup() %>% 
  group_by(seasonId) %>% 
  mutate(MinActualMinusExpWins = min(ActualMinusExpWins)) %>% 
  ungroup() %>% 
  filter(ActualMinusExpWins == MinActualMinusExpWins) %>% 
  mutate(UnluckiestTeam = str_c(firstName 
                                ,": " 
                                ,round(ActualMinusExpWins ,digits = 1) 
                                ," wins below expected"
                                )
         ) %>% 
  select(seasonId ,UnluckiestTeam)

```

Leaderboard
=======================================================================

Sidebar {data-width=200 .sidebar}
-----------------------------------------------------------------------

### Filters

```{r}

# selectInput("PlayerInput"
#             ,"Select a player:"
#             ,choices = PlayerNames
#             ,selected = TopWinPercentPlayer)

selectInput("YearInput"
            ,"Select year(s):"
            ,choices = SeasonYears
            ,selected = SeasonYears
            ,multiple = TRUE)

```


Column {data-width=450}
-----------------------------------------------------------------------

### Regular Season Total Points

```{r}

renderPlot({
LongScoringData %>%  
    filter(WeekType == "Regular" & seasonId %in% input$YearInput) %>%
    group_by(firstName) %>% 
    mutate(NameAppearances = n()) %>% 
    ungroup() %>% 
    mutate(MaxAppearances = max(NameAppearances)) %>% 
    filter(NameAppearances == MaxAppearances) %>%
    arrange(firstName ,seasonId ,matchupPeriodId) %>%
    group_by(firstName) %>% 
    summarise(TotalPoints = sum(TotalPoints)) %>%
    ungroup() %>% 
    ggplot(aes(x = reorder(firstName ,TotalPoints) ,y = TotalPoints ,fill = TotalPoints)) +
    # ggplot(aes(x = reorder(firstName ,TotalPoints) ,y = TotalPoints)) +
      geom_col() +
      coord_flip() +
      scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = pretty_breaks()) +
      scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")) +
      guides(fill ="none") +
      theme_fivethirtyeight()
})

```


### Regular Season Wins

```{r}

renderPlot({
  LongScoringData %>%  
    filter(WeekType == "Regular" & seasonId %in% input$YearInput) %>%
    group_by(firstName) %>% 
    mutate(NameAppearances = n()) %>% 
    ungroup() %>% 
    mutate(MaxAppearances = max(NameAppearances)) %>% 
    filter(NameAppearances == MaxAppearances) %>%    
    arrange(firstName ,seasonId ,matchupPeriodId) %>%
    group_by(firstName) %>% 
    summarise(Weeks             = str_c(seasonId ,matchupPeriodId ,sep = " ") %>% n_distinct()
              ,ExpWin           = sum(ExpWins)
              ,ActualWin        = sum(Win)
              ,ExpWinPercent    = ExpWin / Weeks
              ,ActualWinPercent = ActualWin / Weeks) %>%
    select(-Weeks ,-contains("Percent")) %>% 
    ungroup() %>% 
    pivot_longer(names_to = "WinType" ,values_to = "Wins" ,-firstName) %>% 
    mutate(WinType = if_else(str_detect(WinType ,pattern = "Actual") ,"Actual" ,"Expected")) %>% 
    filter(WinType == "Actual") %>%
    arrange(desc(Wins)) %>%
    mutate(firstName2 = reorder(firstName ,Wins)) %>%
    # bind_rows(TotalWinsData() %>% filter(WinType == "Expected")) %>%
    # mutate(firstName2 = coalesce(firstName2 ,as.factor(firstName))) %>%
    # ggplot(aes(x = firstName2 ,y = Wins ,fill = Wins)) +
    ggplot(aes(x = firstName2 ,y = Wins)) +
      geom_col() +
      coord_flip() +
      # geom_hline(yintercept = 0.5) +
      # facet_wrap(. ~ WinType) +
      # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")) +
      # guides(fill ="none") +
      scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = pretty_breaks()) +
      theme_fivethirtyeight()
})


```


Column {data-width=350}
-----------------------------------------------------------------------

### Seasons

```{r}

renderValueBox({
  valueBox(length(input$YearInput)
           ,icon = "far fa-calendar-alt"
           )
})

```


### Championships Won

```{r}

BreakFunction <- function(k) {
        step <- k
        function(y) seq(floor(min(y)), ceiling(max(y)), by = step)       
}

renderPlot({
  OwnerTeamData %>% 
    mutate(firstName = str_trim(firstName)) %>% 
    filter(seasonId %in% input$YearInput) %>%
    group_by(firstName) %>% 
    mutate(NameAppearances = n()) %>% 
    ungroup() %>% 
    mutate(MaxAppearances = max(NameAppearances)) %>% 
    filter(NameAppearances == MaxAppearances) %>%  
    group_by(firstName) %>% 
    summarise(Championship = sum(Championship)) %>% 
    ggplot(aes(x = reorder(firstName ,Championship) ,y = Championship ,fill = Championship)) +
      geom_col() +
      coord_flip() +
      scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")) +
      guides(fill ="none") +
      scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = BreakFunction(1)) +
      theme_fivethirtyeight()
})

```

### Playoff Appearances

```{r}

renderPlot({
  OwnerTeamData %>% 
    mutate(firstName = str_trim(firstName)) %>% 
    filter(seasonId %in% input$YearInput) %>%
    group_by(firstName) %>% 
    mutate(NameAppearances = n()) %>% 
    ungroup() %>% 
    mutate(MaxAppearances = max(NameAppearances)) %>% 
    filter(NameAppearances == MaxAppearances) %>%  
    group_by(firstName) %>% 
    summarise(PlayoffAppearances = sum(PlayoffAppearance)) %>% 
    ggplot(aes(x = reorder(firstName ,PlayoffAppearances) ,y = PlayoffAppearances ,fill = PlayoffAppearances)) +
      geom_col() +
      coord_flip() +
      scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")) +
      guides(fill ="none") +
      scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = BreakFunction(1)) +
      theme_fivethirtyeight()
})

```


Statistics
=======================================================================

Sidebar {data-width=200 .sidebar}
-----------------------------------------------------------------------

### Filters

```{r}

# selectInput("PlayerInput"
#             ,"Select a player:"
#             ,choices = PlayerNames
#             ,selected = TopWinPercentPlayer)

selectInput("YearInput2"
            ,"Select year(s):"
            ,choices = SeasonYears
            ,selected = SeasonYears
            ,multiple = TRUE)

```


Column {data-width=450}
-----------------------------------------------------------------------

### Regular Season Expected Wins

```{r}
ExpWinsData <- reactive({
  LongScoringData %>%  
    filter(WeekType == "Regular" & seasonId %in% input$YearInput2) %>%
    group_by(firstName) %>% 
    mutate(NameAppearances = n()) %>% 
    ungroup() %>% 
    mutate(MaxAppearances = max(NameAppearances)) %>% 
    filter(NameAppearances == MaxAppearances) %>%    
    arrange(firstName ,seasonId ,matchupPeriodId) %>%
    group_by(firstName) %>% 
    summarise(Weeks             = str_c(seasonId ,matchupPeriodId ,sep = " ") %>% n_distinct()
              ,ExpWin           = sum(ExpWins)
              ,ActualWin        = sum(Win)
              ,ExpWinPercent    = ExpWin / Weeks
              ,ActualWinPercent = ActualWin / Weeks) %>%
    select(-Weeks ,-contains("Percent")) %>% 
    ungroup() %>% 
    pivot_longer(names_to = "WinType" ,values_to = "Wins" ,-firstName) %>% 
    mutate(WinType = if_else(str_detect(WinType ,pattern = "Actual") ,"Actual" ,"Expected"))
})


renderPlot({
  ExpWinsData() %>%
    filter(WinType == "Expected") %>%
    arrange(desc(Wins)) %>%
    mutate(firstName2 = reorder(firstName ,Wins)) %>%
    # bind_rows(TotalWinsData() %>% filter(WinType == "Expected")) %>%
    # mutate(firstName2 = coalesce(firstName2 ,as.factor(firstName))) %>%
    # ggplot(aes(x = firstName2 ,y = Wins ,fill = Wins)) +
    ggplot(aes(x = firstName2 ,y = Wins)) +
      geom_col() +
      coord_flip() +
      # geom_hline(yintercept = 0.5) +
      # facet_wrap(. ~ WinType) +
      # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")) +
      # guides(fill ="none") +
      scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = pretty_breaks()) +
      theme_fivethirtyeight()
})


```


### Regular Season Actual minus Expected Wins

```{r}

renderPlot({
  LongScoringData %>%  
    filter(WeekType == "Regular" & seasonId %in% input$YearInput2) %>%
    group_by(firstName) %>%
    summarise(ActualWins = sum(Win)
              ,ExpWins   = sum(ExpWins)) %>%
    ungroup() %>% 
    mutate(ActualMinusExpWins = ActualWins - ExpWins) %>%
    ggplot(aes(x = reorder(firstName ,ActualMinusExpWins) ,y = ActualMinusExpWins ,fill = ActualMinusExpWins)) +
      geom_col() +
      coord_flip() +
      scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = pretty_breaks()) +
      scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")) +
      guides(fill ="none") +    
      theme_fivethirtyeight()  
})

```


Column {data-width=350}
-----------------------------------------------------------------------

### Regular Season Games

```{r}

renderValueBox({
  valueBox(LongScoringData %>%  
             filter(WeekType == "Regular" & seasonId %in% input$YearInput2) %>% 
             summarise(WeeksPlayed = str_c(seasonId ,matchupPeriodId ,sep = " ") %>% n_distinct())
           ,icon = "fa-football-ball"
           )
})


```

### Total Transactions

```{r}

## This is a ridiculous workaround to setting the order of the columns
## There is 100% a better way to do it
renderPlot({
  OwnerTeamData %>% 
    mutate(firstName = str_trim(firstName)) %>% 
    filter(seasonId %in% input$YearInput2) %>%
    group_by(firstName) %>% 
    mutate(NameAppearances = n()) %>% 
    ungroup() %>% 
    mutate(MaxAppearances = max(NameAppearances)) %>% 
    filter(NameAppearances == MaxAppearances) %>%    
    group_by(firstName) %>% 
    summarise(Acquisitions = sum(transactionCounter.acquisitions)) %>% 
    ggplot(aes(x = reorder(firstName ,Acquisitions) ,y = Acquisitions)) +
      geom_col() +
      coord_flip() +
      scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = pretty_breaks()) +
      theme_fivethirtyeight()
})

```


### Total Trades

```{r}

## This is a ridiculous workaround to setting the order of the columns
## There is 100% a better way to do it
renderPlot({
  OwnerTeamData %>% 
    mutate(firstName = str_trim(firstName)) %>% 
    filter(seasonId %in% input$YearInput2) %>%
    group_by(firstName) %>% 
    mutate(NameAppearances = n()) %>% 
    ungroup() %>% 
    mutate(MaxAppearances = max(NameAppearances)) %>% 
    filter(NameAppearances == MaxAppearances) %>%    
    group_by(firstName) %>% 
    summarise(Trades = sum(transactionCounter.trades)) %>% 
    ggplot(aes(x = reorder(firstName ,Trades) ,y = Trades)) +
      geom_col() +
      coord_flip() +
      scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = pretty_breaks()) +
      theme_fivethirtyeight()
})

```


Owner Performance
=======================================================================

Sidebar {data-width=200 .sidebar}
-----------------------------------------------------------------------

### Filters

```{r}

WeekTypes <- LongScoringData %>% select(WeekType) %>% distinct() %>% pull()

selectInput("PlayerInput"
            ,"Select a player:"
            ,choices = PlayerNames
            ,selected = TopWinPercentPlayer)

selectInput("MatchupType"
            ,"Matchup Period:"
            ,choices = WeekTypes
            ,selected = c("Regular" ,"Playoffs")
            ,multiple = TRUE)

# selectInput("YearInput3"
#             ,"Select year(s):"
#             ,choices = SeasonYears
#             ,selected = SeasonYears
#             ,multiple = TRUE)

```


Column {data-width=450}
-----------------------------------------------------------------------

### Championships

```{r}

MaxChampionships <- OwnerTeamData %>% 
    mutate(firstName = str_trim(firstName)) %>% 
    group_by(firstName) %>% 
    summarise(Championship = sum(Championship)) %>% 
    ungroup() %>% 
    summarise(MaxChampionships = max(Championship))

ReactiveChampionships <- reactive({
  OwnerTeamData %>% 
    mutate(firstName = str_trim(firstName)) %>% 
    filter(firstName == input$PlayerInput) %>%
    summarise(Championship = sum(Championship)) %>% 
    select(Championship)
})

renderValueBox(
  valueBox(ReactiveChampionships()
           ,icon = "fas fa-trophy"
           ,color = if_else(ReactiveChampionships() == 0
                           ,"danger"
                           , if_else(ReactiveChampionships() == MaxChampionships
                                     ,"success" 
                                     ,"warning")))
)


```


### Point Margin by Opponent

```{r}

ReactiveMaxMargin <- reactive({
  OpponentData %>%
    filter(WeekType %in% input$MatchupType) %>%
    group_by(Owner ,Opponent) %>% 
    summarise(PointMargin = sum(PointMargin)) %>% 
    ungroup() %>% 
    summarise(MaxMargin = max(PointMargin)) %>% 
    pull()
})


renderPlot({
  OpponentData %>% 
    filter(Owner == input$PlayerInput & WeekType %in% input$MatchupType) %>% 
    group_by(Opponent) %>% 
    summarise(PointMargin = sum(PointMargin)) %>% 
    ungroup() %>% 
    ggplot(aes(x = reorder(Opponent ,PointMargin) ,y = PointMargin ,fill = PointMargin)) +
    # ggplot(aes(x = reorder(firstName ,TotalPoints) ,y = TotalPoints)) +
      geom_col() +
      coord_flip() +
      scale_y_continuous(labels = comma_format(accuracy = 1) 
                         ,breaks = pretty_breaks()
                         ,limits = c(-ReactiveMaxMargin() ,ReactiveMaxMargin())
                         ) +
      scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")
                           ,limit = c(-ReactiveMaxMargin() ,ReactiveMaxMargin())
                           ) +
      guides(fill ="none") +
      theme_fivethirtyeight()
})



```


### Games Played by Opponent

```{r}

renderPlot({
  OpponentData %>% 
    filter(Owner == input$PlayerInput & WeekType %in% input$MatchupType) %>% 
    group_by(Opponent) %>% 
    summarise(GamesPlayed = n()
              ,TotalWins  = sum(Win)
              ,WinPercent = TotalWins / GamesPlayed) %>% 
    ungroup() %>% 
    # ggplot(aes(x = reorder(Opponent ,GamesPlayed) ,y = GamesPlayed ,fill = GamesPlayed)) +
    ggplot(aes(x = reorder(Opponent ,GamesPlayed) ,y = GamesPlayed)) +
      geom_col() +
      coord_flip() +
      scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = pretty_breaks()) +
      # scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")) +
      guides(fill ="none") +
      theme_fivethirtyeight()
})

```

Column {data-width=350}
-----------------------------------------------------------------------

### Win Percent

```{r}

## May want to only include the teams that made the playoffs?
ReactiveWinPercent <- reactive({
  LongScoringData %>% 
    filter(firstName == input$PlayerInput & WeekType %in% input$MatchupType) %>% 
    summarise(GamesPlayed = n()
              ,Wins       = sum(Win)
              ,WinPercent = round((Wins / GamesPlayed) ,3) * 100
              ) %>% 
    
    select(WinPercent) %>% 
    pull()
})

renderGauge({
  gauge(ReactiveWinPercent()
        ,min = 0 
        ,max = 100 
        ,symbol = '%'
        ,sectors = gaugeSectors(success = c(55 ,100) ,warning = c(45 ,54.9) ,danger = c(0 ,44.9)))
})

```

### Win Percent by Opponent

```{r}

renderPlot({
  OpponentData %>% 
    filter(Owner == input$PlayerInput & WeekType %in% input$MatchupType) %>% 
    group_by(Opponent) %>% 
    summarise(GamesPlayed = n()
              ,TotalWins  = sum(Win)
              ,WinPercent = TotalWins / GamesPlayed) %>% 
    ungroup() %>% 
    ggplot(aes(x = reorder(Opponent ,WinPercent) ,y = WinPercent ,fill = WinPercent)) +
    # ggplot(aes(x = reorder(Opponent ,WinPercent) ,y = WinPercent)) +
      geom_col() +
      geom_hline(yintercept = ReactiveWinPercent() / 100) +  
      coord_flip() +
      scale_y_continuous(labels = percent ,limits = c(0 ,1) ,breaks = pretty_breaks()) +
      scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")) +
      guides(fill ="none") +
      theme_fivethirtyeight()
})


```


### Score Distribution

```{r}

renderPlot({
  LongScoringData %>% 
  filter(firstName == input$PlayerInput & WeekType %in% input$MatchupType) %>% 
  # filter(firstName == "RoBert" & WeekType %in% c("Regular" ,"Playoffs")) %>% 
  ggplot(aes(x = seasonId ,y = TotalPoints)) +
    geom_violin(aes(group = seasonId) ,draw_quantiles = c(0.5)) +
    geom_jitter(height = 0, width = 0.05) +
    geom_smooth(se = FALSE) +
    scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = pretty_breaks()) +
    theme_fivethirtyeight()
})

# LongScoringData %>%
#   # filter(firstName == input$PlayerInput & WeekType %in% input$MatchupType) %>%
#   filter(firstName == "RoBert" & WeekType %in% c("Regular" ,"Playoffs")) %>%
#   ggplot(aes(x = seasonId ,y = TotalPoints)) +
#     geom_violin(aes(group = seasonId) ,draw_quantiles = c(0.5)) +
#     geom_jitter(height = 0, width = 0.05) +
#     geom_smooth(se = FALSE) +
#     scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = pretty_breaks()) +
#     theme_fivethirtyeight()
    

```



Season Recaps
=======================================================================

Column {data-width=1000}
-----------------------------------------------------------------------

### Seasons in Review

```{r}

SeasonRecap <- Champion %>% 
  left_join(BestTeam ,by = "seasonId") %>% 
  left_join(TopScorer ,by = "seasonId") %>% 
  left_join(LuckiestTeam ,by = "seasonId") %>%
  left_join(WorstTeam ,by = "seasonId") %>% 
  left_join(LowestScorer ,by = "seasonId") %>% 
  left_join(UnluckiestTeam ,by = "seasonId") %>% 
  rename(Season = seasonId) %>% 
  arrange(Season)

colnames(SeasonRecap) <- str_replace(colnames(SeasonRecap) ,pattern = "([[:lower:]])([[:upper:]])" ,replacement = "\\1 \\2")


datatable(SeasonRecap)

```







```{r ,include = FALSE}
### Regular Season Win Streak

WinStreakData <- reactive({
  LongScoringData %>%
    filter(WeekType == "Regular" & seasonId %in% input$YearInput2) %>%
    group_by(firstName) %>% 
    mutate(NameAppearances = n()) %>% 
    ungroup() %>% 
    mutate(MaxAppearances = max(NameAppearances)) %>% 
    filter(NameAppearances == MaxAppearances) %>%        
    arrange(firstName ,seasonId ,matchupPeriodId) %>%
    group_by(firstName) %>%
    summarise(LongestLoseStreak  = max(rle(Win)$lengths[rle(Win)$values==0])
              ,LongestWinStreak  = max(rle(Win)$lengths[rle(Win)$values==1])
              ,CurrentLoseStreak = ifelse(rle(Win)$values[length(rle(Win)$values)]==0 ,rle(Win)$lengths[rle(Win)$values==0][length(rle(Win)$lengths[rle(Win)$values==0])] ,0)
              ,CurrentWinStreak  = ifelse(rle(Win)$values[length(rle(Win)$values)]==1 ,rle(Win)$lengths[rle(Win)$values==1][length(rle(Win)$lengths[rle(Win)$values==1])] ,0)
              ) %>%
  gather(key = "StreakType" ,value = "Streak" ,-firstName) %>%
  mutate(Outcome     = ifelse(str_detect(StreakType ,pattern = "Win") ,"Win" ,"Lose")
         ,LengthType = ifelse(str_detect(StreakType ,pattern = "Longest") ,"Longest" ,"Current") %>%
                          factor(levels = c("Longest" ,"Current"))
         ) %>%
  select(firstName:StreakType ,Outcome:LengthType ,Streak) %>%
    filter(Outcome == "Win")
})

## This is a ridiculous workaround to setting the order of the columns
## There is 100% a better way to do it
renderPlot({
  WinStreakData() %>%
    filter(LengthType == "Longest") %>%
    arrange(desc(Streak)) %>%
    mutate(firstName2 = reorder(firstName ,Streak)) %>%
    bind_rows(WinStreakData() %>% filter(LengthType == "Current")) %>%
    mutate(firstName2 = coalesce(firstName2 ,as.factor(firstName))) %>%
    ggplot(aes(x = firstName2 ,y = Streak ,fill = Streak)) +
      geom_col() +
      coord_flip() +
      facet_wrap(. ~ LengthType) +
      scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = pretty_breaks()) +
      scale_fill_gradientn(colors = c("darkred", "tomato1","palegreen", "darkgreen")) +
      guides(fill ="none") +
      theme_fivethirtyeight()
})

```



```{r ,include=FALSE}
### Regular Season Lose Streak

LoseStreakData <- reactive({
  LongScoringData %>%  
    filter(WeekType == "Regular" & seasonId %in% input$YearInput2) %>%
    group_by(firstName) %>% 
    mutate(NameAppearances = n()) %>% 
    ungroup() %>% 
    mutate(MaxAppearances = max(NameAppearances)) %>% 
    filter(NameAppearances == MaxAppearances) %>%        
    arrange(firstName ,seasonId ,matchupPeriodId) %>%
    group_by(firstName) %>%
    summarise(LongestLoseStreak  = max(rle(Win)$lengths[rle(Win)$values==0])
              ,LongestWinStreak  = max(rle(Win)$lengths[rle(Win)$values==1])
              ,CurrentLoseStreak = ifelse(rle(Win)$values[length(rle(Win)$values)]==0 ,rle(Win)$lengths[rle(Win)$values==0][length(rle(Win)$lengths[rle(Win)$values==0])] ,0)
              ,CurrentWinStreak  = ifelse(rle(Win)$values[length(rle(Win)$values)]==1 ,rle(Win)$lengths[rle(Win)$values==1][length(rle(Win)$lengths[rle(Win)$values==1])] ,0)
              ) %>%
  gather(key = "StreakType" ,value = "Streak" ,-firstName) %>%
  mutate(Outcome     = ifelse(str_detect(StreakType ,pattern = "Win") ,"Win" ,"Lose")
         ,LengthType = ifelse(str_detect(StreakType ,pattern = "Longest") ,"Longest" ,"Current") %>%
                          factor(levels = c("Longest" ,"Current"))
         ) %>%
  select(firstName:StreakType ,Outcome:LengthType ,Streak) %>%
    filter(Outcome == "Lose")
})

## This is a ridiculous workaround to setting the order of the columns
## There is 100% a better way to do it
renderPlot({
  LoseStreakData() %>%
    filter(LengthType == "Longest") %>% 
    arrange(desc(Streak)) %>%
    mutate(firstName2 = reorder(firstName ,Streak)) %>% 
    bind_rows(LoseStreakData() %>% filter(LengthType == "Current")) %>%
    mutate(firstName2 = coalesce(firstName2 ,as.factor(firstName))) %>% 
    ggplot(aes(x = firstName2 ,y = Streak ,fill = Streak)) +
      geom_col() +
      coord_flip() +
      facet_wrap(. ~ LengthType) +
      scale_y_continuous(labels = comma_format(accuracy = 1) ,breaks = pretty_breaks()) +
      scale_fill_gradientn(colors = c("darkgreen", "palegreen","tomato1", "darkred")) +
      guides(fill ="none") +    
      theme_fivethirtyeight()  
})

```










